meta_product_name: "Skill-Up"
meta_title: "Teach your skills, earn points and learn new skills for free!"
meta_description: "You want to learn a new skill but have no money to pay for an expensive course?

With Skill-Up you can learn new skills for free!

All you have to do is teach others, earn points and use those points to learn a new skill."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
